### ISSUE TITLE
flowers.hd5

### ISSUE THREAD

**Issue by Edakksm** [aelnouby/Text-to-Image-Synthesis#14]
I downloaded flowers.hdf5. 
Confused on how to proceed further.
How do I get the following?

flowers_images_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/'
flowers_embedding_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/'
flowers_text_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/cvpr2016_flowers/text_c10/'
flowers_dataset_path: '/scratch/aelnouby/text2image/flowers.hdf5'

flowers_val_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/valclasses.txt'
flowers_train_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/trainclasses.txt'
flowers_test_split_path: '/export/mlrg/aelnouby/projects/GANs/flowers_dataset/flowers_icml/testclasses.txt'

**Comment by aelnouby** [comment]
If you downloaded the hdf5 file you only need to modify this line from

` flowers_dataset_path: '/scratch/aelnouby/text2image/flowers.hdf5'`

 to

` flowers_dataset_path: PATH TO HD5 FILE`


The other key value pairs are needed if you want to create the hdf5 file yourself.

**Comment by satvikrishna** [comment]
Thank you. I will try it out.

**Comment by satvikrishna** [comment]
I uploaded hdf5 to the right path. Thank you
But now when I try python runtime.py, I get the following exception. Is it trying to access /events or something?

requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection
.HTTPConnection object at 0x7f79237f5198>: Failed to establish a new connection: [Errno 111] Connection refused',))

**Comment by aelnouby** [comment]
This error is from Visdom. It is used for visualization. Install it and follow the guide here to run it https://github.com/facebookresearch/visdom
